services:
  rules-engine-poc-jbpm:
    build:
      context: .
      target: production
    image: rules-engine-poc-jbpm
    container_name: rules-engine-poc-jbpm
    environment:
      APPINSIGHTS_CLOUDROLE: rules-engine-poc-jbpm-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      COOKIE_PASSWORD: ${COOKIE_PASSWORD}
