services:
  ffc-techspike-rules-engine:
    build:
      context: .
      target: production
    image: ffc-techspike-rules-engine
    container_name: ffc-techspike-rules-engine
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-rules-engine-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      COOKIE_PASSWORD: ${COOKIE_PASSWORD}
      BASE_URL: ${BASE_URL}
      JBPM_URL: ${JBPM_URL}
      ELIGIBILITY_PROCESS_DEFINITION_ID: ${ELIGIBILITY_PROCESS_DEFINITION_ID}
      POC_CONTAINER_ID: ${POC_CONTAINER_ID}
      PROCESS_SUFFIX: ${PROCESS_SUFFIX}
      REST_USERNAME: ${REST_USERNAME}
      REST_PASSWORD: ${REST_PASSWORD}
