# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  rules-engine-poc-jbpm:
    build:
      target: development
    image: rules-engine-poc-jbpm-development
    container_name: rules-engine-poc-jbpm-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
