services:
  rules-engine-poc-jbpm:
    build:
      context: .
      target: production
    image: rules-engine-poc-jbpm
    container_name: rules-engine-poc-jbpm
    environment:
      APPINSIGHTS_CLOUDROLE: rules-engine-poc-jbpm-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      COOKIE_PASSWORD: ${COOKIE_PASSWORD}
      BASE_URL: ${BASE_URL}
      JBPM_URL: ${JBPM_URL}
      ELIGIBILITY_PROCESS_DEFINITION_ID: ${ELIGIBILITY_PROCESS_DEFINITION_ID}
      POC_CONTAINER_ID: ${POC_CONTAINER_ID}
      PROCESS_PREFIX: ${PROCESS_PREFIX}
      REST_USERNAME: ${REST_USERNAME}
      REST_PASSWORD: ${REST_PASSWORD}
