{{- include "ffc-helm-library.container-secret" (list . "rules-engine-poc-jbpm.container-secret") -}}
{{- define "rules-engine-poc-jbpm.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
{{- end -}}
