{{- include "ffc-helm-library.deployment" (list . "ffc-techspike-rules-engine.deployment") -}}
{{- define "ffc-techspike-rules-engine.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-techspike-rules-engine.container") }}
{{- end -}}
